### ISSUE TITLE
Compilation Warnings

### ISSUE THREAD

**Issue by AmanSingh001** [shanhashcah/HCX#1]
After running apt-get update command getting some compilation warnings.

**Comment by DebjitSen** [comment]
There are few steps to perform above command.
A simple command line tool, the apt-get command performs the functions of installing, removing, updating and upgrading a package. The commands used for these functions are discussed in brief.

Installing a package : sudo apt-get install

Removing a package : sudo apt-get remove

Updating a package : sudo apt-get update

Upgrading a package : sudo apt-get upgrade

For information about the command : apt-get help
